export const apiConstants = {
    
    API_LOGOUT_SUCCESS:'API_LOGOUT_SUCCESS',
    CITY_WEATHER_LOAD:"CITY_WETHER_LOAD",
    CITY_WEATHER_SUCCESS:'CITY_WEATHER_SUCCESS',
    CITY_WEATHER_FAIL:"CITY_WEATHER_FAIL",
    CITY_WEATHER_ERROR:"CITY_WEATHER_ERROR",

    //all weather data
    API_ALL_WEATHER_DATA_LOAD:"API_ALL_WEATHER_DATA_LOAD",
    API_ALL_WEATHER_DATA_SUCCESS:"API_ALL_WEATHER_DATA_SUCCESS",
    API_ALL_WEATHER_DATA_FAIL:"API_ALL_WEATHER_DATA_FAIL",
    API_ALL_WEATHER_DATA_ERROR:"API_ALL_WEATHER_DATA_ERROR",

    //Search city weather data
    API_SEARCH_CITY_LOAD:"API_SEARCH_CITY_LOAD",
    API_SEARCH_CITY_SUCCESS:"API_SEARCH_CITY_SUCCESS",
    API_SEARCH_CITY_FAIL:"API_SEARCH_CITY_FAIL",
    API_SEARCH_CITY_ERROR:"API_SEARCH_CITY_ERROR",

    //set AsuncStorage Data
    SET_STORAGE_DATA:"SET_STORAGE_DATA",

    //delet City
    Delete_CITY:"Delete_CITY"
    };
  